gitops:
  namespaceScoped: true

catalog:
  name: ibm-operator-catalog
  displayName: IBM operator Catalog
  image: icr.io/cpopen/ibm-operator-catalog

subscription:
  wsaOperatorNamespace: ''
  channel: v1.11
  installPlanApproval: Automatic
  wsaInstanceNamespace: ''

operatorNamespace: ''

commonServicesNamespace: ''

licensingNamespace: ''

certManagerNamespace: ''

wsaHealth:
  spec:
    license:
      accept: ''

wsaSecure:
  spec:
    license:
      accept: ''      

wsa:
  spec:
    commonServices:
      registryNamespace: ''
    license:
      accept: ''